# Descriptive statistics problems

### Exercise 1

We will use NumPy to obtain information to describe statistically.

- Generate an array of 100 elements following a normal distribution.
- Generate an array of 100 elements following a chi-square distribution with 3 degrees of freedom.
- Calculate the main metrics and statistical measures that best describe the two vectors.

In [1]:
# TODO
import numpy as np
np.random.normal(10,1,100)



array([10.19781225, 11.75163348,  8.97559389, 11.09436231,  9.12397423,
       10.27199018, 10.60493513,  9.94868253, 10.54638485, 10.38621211,
       10.06551073,  9.08709646, 11.10439784, 11.63177316, 10.21495597,
       10.14563458, 10.26667378,  8.10228799,  8.75859417,  9.22649732,
       10.97325165,  9.45043839, 11.25671996, 10.25787356,  8.65027111,
       10.59568021, 10.72845981,  9.35537289, 10.05473778, 10.58988352,
       11.69547266, 12.28834769,  8.54492065,  8.18715274, 10.22399281,
       10.24586502,  8.14794768,  9.73477824, 10.69399158,  8.73308882,
        8.27718158, 11.24302392, 10.71296094,  8.78195998,  8.85242663,
        9.00779399,  9.96604352, 11.47940266, 10.25172905,  9.96899103,
       10.92834178, 10.11248523, 11.35228583, 10.1556348 ,  8.37970892,
        8.49273563,  8.70503989, 10.50405638, 11.12285892, 10.14606781,
       11.48136018,  8.74388763,  8.1339009 ,  8.69606697,  9.32220635,
       10.14928489, 12.07384946, 11.01145001,  9.0424734 ,  6.08

In [2]:
np.random.chisquare(3,100)

array([ 7.1740653 ,  2.10263723,  2.1694699 ,  3.16137284,  4.50119283,
        3.36120777,  2.21728138,  3.3470369 ,  7.79870914,  0.25549252,
        3.64571618,  1.69924435,  4.14635407,  4.951268  ,  1.97983134,
       19.98960509, 10.23155578,  3.43875062,  1.72407799,  1.96469557,
        0.74137601,  1.22729286,  2.3522906 ,  1.06347391,  2.3657686 ,
        3.74008382,  2.04100213,  1.93445854,  4.00427447,  8.74896951,
        3.50818119,  1.26506079,  2.55208842,  4.97267789,  2.8984858 ,
        4.29174128,  1.08522733,  0.81732075,  0.87286886,  4.49764269,
        2.07175812,  0.82562317,  2.48997363,  0.24201669,  0.79352034,
        7.45676512,  3.85349894,  1.53434133, 14.48626553,  3.73621929,
        0.59131789,  1.61853226,  4.35790016,  3.33822917,  0.86517513,
        0.16420144,  0.5835286 ,  6.01987103,  3.48599628,  5.09718046,
        3.42558357,  1.13201716,  1.85532794,  0.2544319 ,  3.12020602,
        2.80486211,  7.97403937,  0.56252993,  2.65672271,  2.38

In [3]:
np.random.chisquare(3,100)

array([ 1.15120767,  3.19469211,  1.21333176,  4.02898742,  1.79270394,
        8.21845851,  4.65471796,  0.12902118,  1.85059321,  2.19576464,
        1.13367538,  0.70929493,  0.55784747,  1.30420862,  1.25725717,
        2.4387154 ,  0.67025107,  1.20294382, 12.50237067,  3.5219451 ,
        0.96684488,  2.06058135,  0.82482684,  1.5467624 ,  1.43677863,
        3.68447708,  4.21831344,  4.78928234,  2.48010611,  4.98092988,
        2.28301863,  5.29541008,  1.38310273,  4.32235835,  1.34251776,
        6.2138881 ,  3.76481785,  6.25389577,  2.87114334,  1.68734187,
        5.06064222,  6.30267529,  1.69123303,  1.53255183,  0.47272488,
        0.26729358,  8.15133872,  1.26000782,  2.59886148,  2.99075768,
        0.61476066,  0.616669  ,  1.0378156 ,  1.21328616,  2.07390998,
        6.59530484,  6.40224604,  0.05403408,  4.63596527,  1.3507196 ,
        5.11263069,  9.83761632,  5.44872084,  2.69567911,  5.10609783,
        2.78840537,  3.21212876, 11.51692612,  2.04204033,  4.98

In [4]:
import statistics as stats 
chisquare=np.random.chisquare(3,100)
normal_distribution=np.random.normal(10,1,100)
mode_1=stats.mode(chisquare)
print(mode_1)

4.26829520192589


In [5]:
median_2=stats.median(normal_distribution)
print(median_2)

9.909169889597079


In [6]:
median_1=stats.median(chisquare)
print(median_1)

2.2956914640875086


In [7]:
mean_2=stats.mean(normal_distribution)
print(mean_2)

9.90830911573522


In [8]:
mean_1=stats.mean(chisquare)
print(mean_1)

2.832228212580985


In [9]:
mode_2=stats.mode(normal_distribution)
print(mode_2)

8.956504313827088


In [10]:
range1=max(normal_distribution)-min(normal_distribution)
print(range1)

5.122953153223217


In [11]:
range_2=max(chisquare)-min(chisquare)
print(range_2)

11.290568675087272


In [12]:
variance1=stats.variance(normal_distribution)
print(variance1)

1.1307950440628438


In [13]:
variance2=stats.variance(chisquare)
print(variance2)

4.851310340590474


In [14]:
std_1=stats.stdev(chisquare)
print(std_1)

2.2025690319693667


In [15]:
std_2=stats.stdev(normal_distribution)
print(std_2)

1.0633884727900917


In [16]:
from scipy.stats import skew, kurtosis
skew_1=skew(normal_distribution)
print(skew_1)

0.026293642629107664


In [17]:
skew_2=skew(chisquare)
print(skew_2)

1.2523448072231766


In [18]:
kurtosis_1=kurtosis(normal_distribution)
print(kurtosis_1)

-0.49171111710329063


In [19]:
kurtosis_2=kurtosis(chisquare)
print(kurtosis_2)

1.7130958936516407


### Exercise 2

Write a Python program to calculate the standard deviation of the following data:

```py
data = [4, 2, 5, 8, 6]
```

In [23]:
# TODO
import math, sys
data = [4, 2, 5, 8, 6]
def sd_calc(data):
    n=len(data)
    if (n<=1):
        return 0
    mean,sd=avg_calc(data),0.0
    for d in data:
        sd+=(float(d)-mean)**2
    sd = math.sqrt(sd/float(n-1))
    return sd

def avg_calc(data):
    n,mean = len(data),0.0
    if (n<=1):
        return data[0]
    for d in data 
        mean= mean+float(d)
       mean=mean/float(n)
    return mean
print(f"sample data: {data}")
print(f"standard deviation: {sd_calc(data)}")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 20)